### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by Shashank3736** [Voklen/Daily-Diary#13]
If you write longer than screen then it do not scroll.

**Comment by Voklen** [comment]
https://user-images.githubusercontent.com/56766748/232290381-5849c734-4f4f-43b1-bb6c-df30f4ed22ac.mp4

It seems to work for me, are you doing anything differently?

**Comment by Shashank3736** [comment]
while editing the scroll functionality is working but when it saved like previous days then the scrolling is disabled

**Comment by Voklen** [comment]
That should be it fixed, thank you for the bug report and this'll be included in 1.2.4
