### ISSUE TITLE
I changed the directory on a non-rooted device, now my entries are gone?

### ISSUE THREAD

**Issue by ErikUden** [Voklen/Daily-Diary#16]
I was looking for a way to export my written diary entries, so I sadly ignored the warning that this would not work without root. 

The phone I did this on is non-rooted, is there any way to recover my files? I cannot access the folder and set the setting back to its original state (_I assume that was where all the files that made up the notes were stored, hence changing that makes the app lose track of where those notes are_)!

Is there anything I can do? Maybe in a next update you could add a button to restore that setting and or export the notes into a format that can be imported by the same app (or just as markdown files)!

Super grateful for your development, love the concept of Daily Diary!

**Comment by Voklen** [comment]
By default the notes are stored at `/storage/emulated/0/Android/data/com.voklen.daily_diary/files/` and your entries should still be there. The app stores it as plaintext files so they can be transferred and edited on any device. There's already a button to restore settings at the top that says "Select settings to reset".

<img src="https://github.com/Voklen/Daily-Diary/assets/56766748/6c5d2058-fa9d-49a4-a0df-e34166452f69" alt="Daily Diary settings page" width="300">

That being said, I am working on using scoped storage so you can change the directory on non-rooted devices and on a feature to add an export button that compresses that directory as a zip file.

I'm glad you're enjoying Daily Diary, feedback is always appreciated!

**Comment by ErikUden** [comment]
> By default the notes are stored at `/storage/emulated/0/Android/data/com.voklen.daily_diary/files/` and your entries should still be there. The app stores it as plaintext files so they can be transferred and edited on any device. There's already a button to restore settings at the top that says "Select settings to reset".
> 
> <img src="https://github.com/Voklen/Daily-Diary/assets/56766748/6c5d2058-fa9d-49a4-a0df-e34166452f69" alt="Daily Diary settings page" width="300">
> 
> That being said, I am working on using scoped storage so you can change the directory on non-rooted devices and on a feature to add an export button that compresses that directory as a zip file.
> 
> I'm glad you're enjoying Daily Diary, feedback is always appreciated!

Oh, thank you very much! All works very well now, I could've figured this one out myself. Thank you for your quick reply!

**Comment by ErikUden** [comment]
Thank you!! Will do ^ ^!
