### ISSUE TITLE
Empty entries in the history

### ISSUE THREAD

**Issue by stephenpcook** [Voklen/Daily-Diary#17]
There are empty files in the "Previous Entries" view.

*Current Behaviour*: In the "Previous Entries" section of the android app, there are days with no text in the diary.  I believe these are days when I opened the app but didn't write anything.

*Expected Behaviour*: Days with no text do not show up in the pervious entries list, just as with days where the app wasn't opened. Alternatively, the user could have a way to mark and delete days, but that probably counts as a separate feature.

**Comment by stephenpcook** [comment]
I should have checked the version and recent commits - looks like this might have been resolved in version 1.2.4 in c9b6a79bfbe0e19788ec336564af79f2c250c111 (I have v1.2.3).

**Comment by stephenpcook** [comment]
After updating, I still have empty entries from before the update - only a minor inconvenience.

**Comment by Voklen** [comment]
Ahh I'm glad you found the fix (nicely written and clear bug report though). I did consider deleting a user's empty files but I then decided that I didn't want to be deleting users existing files, and it would be searching and opening up every file in the directory to check it every time the app runs, and this only affects a few users at the start and will be less and less of a problem over time naturally.
For now, if you want to delete the empty files you can find them all at `/storage/emulated/0/Android/data/com.voklen.daily_diary/files/`
