### ISSUE TITLE
Allow file name customization

### ISSUE THREAD

**Issue by mstmob** [Voklen/Daily-Diary#18]
It would be nice to customize the file name and extension via a date template.

**Proposal**: For example `%Y-%M-%D.md` should be translated to `2023-06-14.md` as the diary file for today.

**Background**: I would like to use markdown files for my diary instead of the default `txt` extension and maybe this would be an opportunity to also allow customizing the file name as the directory can already be adapted...

**Comment by Voklen** [comment]
Hmm, love the idea! I'll get to work on that when I have the chance.

**Comment by Voklen** [comment]
Sorry that it took so long, but now it's in the latest release. F-droid takes a few days to update so if you've got the app from there look out for it in the coming days. Thanks for using the app and I hope you enjoy it!
