### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by wjksiazek** [Voklen/Daily-Diary#21]
The app seems to have problems encoding non-ASCII characters - when I type in Polish characters (used 'Żółć' for tests) it looks ok, but when I close the app and reopen, wrong characters are drawn. The issue is also present for imported notes with Polish characters, encoded with utf-8.

**Comment by Voklen** [comment]
That's interesting, I've got automated tests with Polish characters and regularly write in different scripts (uczę się polskiego). What device are you on?

**Comment by wjksiazek** [comment]
I'm on Oppo Find X3 Neo. Also, good luck with your Polish classes :)

**Comment by Voklen** [comment]
This is such an interesting issue, I still can't replicate it on any of my devices. What device are you using @ivysrono?

**Comment by Voklen** [comment]
There we go! It turns out it only happened when you change the folder of the entries, this fix should make all current and previous entries display correctly now and will be in `v1.4.1`. Thank you both for submitting this problem :+1:
