### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Voklen/Daily-Diary#23]
Looking at this fail https://gitlab.com/fdroid/fdroiddata/-/jobs/5531465714#L1441 

Did you forget to bump flutter version https://github.com/Voklen/Daily-Diary/tree/v1.4.1/submodules ?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/9d189b4f9dbf5defbec3f4af8a3d95b3ae80d9f0

**Comment by Voklen** [comment]
Thank you, I did indeed forget to bump the flutter version, I just noticed this separately as well. I've now updated it and it is now building. Should I update the `metadata/com.voklen.daily_diary.yml` file manually or will `F-Droid checkupdates` automatically see that the release has changed?

**Comment by licaon-kter** [comment]
I've updated, thanks: https://gitlab.com/fdroid/fdroiddata/-/commit/09e830ed22a82a5279f620a74a81a3b6a884c1d6
