### ISSUE TITLE
Not saving on close (repeatable logic bug)

### ISSUE THREAD

**Issue by mgolden356** [Voklen/Daily-Diary#24]
There's a pretty significant repeatable logic bug (on my phone the Moto G 5G stylus (2022) with the latest version of this app, with battery optimization on unrestricted:

Swiping up from the bottom bar and releasing, or circle, to return to the home screen, writes the current notes onto the text file, which is intended and good. Also pressing back, or triangle, until the app closes, also savss the file.

However, swiping up and holding and releasing, or the square button, and then swiping the app away to close, does not save it.

I think that there should be no way to exit the app without it being saved, and the second option doesn't. I know this is not impoasible to implement cause the app ColorNote does it, and even notifies you that this occurs.

----

Btw thank you very much for this awesome app, I love that it makes making txt files really convenient.

**Comment by mgolden356** [comment]
Now that I think about it, perhaps an enhancement could be to press a button to undo and redo the changes since the last save.

**Comment by Voklen** [comment]
Thanks for the report, I can reproduce it but am away right now so I'll fix it when I get back. I'm glad you're enjoying the app!

**Comment by Voklen** [comment]
And that's it fixed, it'll be in the next update so look out for that!
