### ISSUE TITLE
[Request] Allow save directory selection on mobile

### ISSUE THREAD

**Issue by Victor4X** [Voklen/Daily-Diary#3]
I already use syncthing for synchronizing files between devices, and it would be great if I could save my diary entries and config to the folder I have already set up

**Comment by Voklen** [comment]
In fact I was just working on that but only for desktop, I'll add Android support in that case as well

**Comment by quinnzbellz** [comment]
Would it also be possible to add support for exporting notes in an encrypted format? I know personally if someone else were to get into my device I wouldn't want them reading my previous entries, so it would be a nice privacy/security feature.

**Comment by Voklen** [comment]
@quinnzbellz Thanks for the feature request but please create a separate issue for it and then I'll see what I can do.

**Comment by quinnzbellz** [comment]
Alright, I will when I get home!
