### ISSUE TITLE
Copycat/Clone of Daily Diary on Google Play

### ISSUE THREAD

**Issue by Poussinou** [Voklen/Daily-Diary#9]
Hi @Voklen 

I just found this app on Google Play https://play.google.com/store/apps/details?id=com.voklen.daily_diary from [this developer](https://play.google.com/store/apps/developer?id=Schnupfeld).

It's full of ads, and it's clearly a violation of the GNU GPLv3 license...

People from Newpipe wrote a procedure to report the app to Google Play that I collected [here](https://gist.github.com/Poussinou/86136151f8b939fbaa48650666bf62d6) in a gist if it's of some interest for you.

**Comment by Voklen** [comment]
Thank you very much, reported. We'll see what happens.

**Comment by Voklen** [comment]
And that's it taken down, thanks for bringing that to my attention.

**Comment by Poussinou** [comment]
Good news :)

Please report it here if you find other copycats.
